portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("projects.urls", namespace="projects")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.home_page, name="home_page"),
    path("about/", views.about_me, name="about_me"),
    path('projectpage/', views.project, name='project'),
    path("contact/", views.contact, name='contact'),
    path('login/', views.user_login, name="user_login"),
    path('account/', views.dashboard, name="account"),
    path("upload/", views.upload, name="upload"),
    path("update/", views.update, name="update"),
    path("logout/", views.user_logout, name='user_logout'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Me(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL,
                                related_name='users', null=True)

    # additional items
    profile_pic = models.ImageField(upload_to="my_pics", blank=True, null=True)
    background_pic = models.ImageField(
        upload_to="my_pics", blank=True, null=True)
    about_me = models.TextField()

    class Meta:
        verbose_name = "Me"
        verbose_name_plural = "Me"

    def __str__(self):
        return self.user.username

    @property
    def profileURL(self):
        try:
            url = self.profile_pic.url
        except ValueError:
            url = ''
        return url

    @property
    def backgroundURL(self):
        try:
            url_back = self.background_pic.url
        except ValueError:
            url_back = ''
        return url_back


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    software_used = models.CharField(max_length=200)
    project_image = models.ImageField(
        upload_to="project_images", blank=True, null=True)
    url = models.URLField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.title

    @property
    def ImageURL(self):
        try:
            url = self.project_image.url
        except ValueError:
            url = ''
        return url




projects/forms.py
from django import forms
from .models import Project, Me
# from django.contrib.auth.models import User 

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['title','description','url','project_image','software_used']
		widgets = {
			'description':forms.Textarea
		}
		
class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = Me
		fields = ["profile_pic", "background_pic", "about_me"]


projects/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, get_connection
from django.conf import settings
from .models import Me, Project
from . import forms


def home_page(request):
    me = Me.objects.get()
    proj = Project.objects.all()[:4]
    return render(request, 'project/homepage.html', dict(proj=proj, me=me, section="home_page"))


def about_me(request):
    me = Me.objects.get()
    return render(request, "project/aboutpage.html", dict(me=me, section="about_me"))


def project(request):
    projects = Project.objects.all()
    paginator = Paginator(projects, 4)
    page = request.GET.get("page")

    try:
        projects = paginator.page(page)
        # Trying to pick out the number of query(projects) per page
    except PageNotAnInteger:
        # if the page is not an integer deliver first page
        projects = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver the last page of the results.
        projects = paginator.page(paginator.num_pages)
    return render(request, 'project/projectpage.html',
                  dict(projects=projects, page=page))


def contact(request):
    try:
        submitted = False
        if request.method == "POST":
            email = request.POST.get("email_address")
            name = request.POST.get("name")
            subject = request.POST.get("subject")
            message = request.POST.get("message")
            message = name + " said, " + message

            send_mail(subject=subject, message=message,
                      from_email=email,
                      recipient_list=[settings.EMAIL_HOST_USER],
                      fail_silently=False
                      )
            submitted = True

            return render(request, 'project/homepage.html', {'submitted': submitted, "name": name})

    except ValueError:
        return render(request, 'project/homepage.html', {'submitted': submitted})


def user_login(request):
    try:
        if request.method == 'POST':
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    return redirect("projects:account")
                else:
                    return render(request, 'project/login.html', {'error': "Mayokun your account is not active"})
            else:
                return render(request, 'project/login.html', {'error': "Opps! It's only Isaiah Olaoye that can login😃😃"})

        return render(request, 'project/login.html', {})

    except ValueError:
        return render(request, 'project/login.html', {'error': "Bad request"})


@login_required
def dashboard(request):
    return render(request, 'project/account.html')


@login_required
def upload(request):
    try:
        if request.method == 'POST':
            form = forms.ProjectForm(request.POST)

            if form.is_valid():
                form = form.save(commit=False)

                if 'project_image' in request.FILES:
                    form.project_image = request.FILES.get("project_image")

                form.save()
                return redirect("projects:account")
            else:
                return render(request, 'project/upload.html', dict(form=form, error='Fill in the correct info.'))
        else:
            form = forms.ProjectForm()

        return render(request, 'project/upload.html', dict(form=form))

    except ValueError:
        return render(request, 'project/login.html', {'error': "Bad request"})


@login_required
def update(request):

    try:
        info = get_object_or_404(Me, id=1, user=request.user)
        if request.method == 'POST':
            update_form = forms.UserUpdateForm(instance=info,
                                               data=request.POST,
                                               files=request.FILES)
            if update_form.is_valid():
                update_form.save()
                return redirect("projects:account")

        else:
            update_form = forms.UserUpdateForm(instance=info)

        return render(request, 'project/updatepage.html', dict(form=update_form, info=info))

    except ValueError:
        return render(request, 'project/login.html', {'error': "Bad request"})


@login_required
def user_logout(request):
    logout(request)
    return redirect("projects:home_page")

projects/templates/project/aboutpage.html
{% extends 'base.html' %}

{% block title %} {{ me.user.username }}{% endblock %}

{% block content %}

<div class="py-5 z-depth-1">

    <!--Section: Content-->
    <section class="dark-grey-text text-center" style="background-color:#02121ff1;">
        <div class="container">
            <h3 class="font-weight-bold pt-4 mb-4 cyan-text">{{ me.user.username }}</h3>

            <div class="row mx-lg-5 mx-md-3">
                <div class="col-md-6 mb-4">

                    <div class="view mb-5">
                        <img src="{{ me.profileURL }}" class="img-fluid rounded-circle" alt="{{ me.user.username }}">
                    </div>

                    <h5 class="font-weight-normal green-text text-muted">{{ me.about_me }}.</h5>

                </div>
                <div class="col-md-6 mb-4">

                    <div class="view mb-5">
                        <img src="https://mdbootstrap.com/img/illustrations/undraw_basketball_agx4.png"
                            class="img-fluid" alt="bball">
                    </div>

                    <h5 class="font-weight-normal red-text text-muted">I love watching Bball games
                    and love playing Basketball...</h5>
                </div>
            </div>
        </div>
    </section>
    <!--Section: Content-->
</div>

{% endblock %}

projects/templates/project/account.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.css" rel="stylesheet" />
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.js"></script>
    <!-- online iinks -->

    <!-- manual links -->
    <!--logo link-->
    <link rel="icon" href="{% static 'image/kuhmasiilogo.png' %}" type="image/x-icon">

    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <style>
        html,
        body,
        header,
        .view {
            background-color: rgba(71, 69, 69, 0.774);
            height: 100%;
            font-size: 15px;
            font-weight: bold;
            font-family: Georgia, 'Times New Roman', Times, serif;
            font-style: italic;
        }

        #navbarSupportedContent a {
            color: #d6dde2;
        }

        #navbarSupportedContent a:hover {
            color: #5985a3;
        }
    </style>

</head>

<body>
    <navbar>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg">
            <!-- Container wrapper -->
            <div class="container">
                <!-- Toggle button -->
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-togggler-icon d-flex justify-content
                    -start align-items-center">
                        <i class="fas fa-bars text-white"></i>
                    </span>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'projects:home_page' %}">Home</a>
                        </li>
                    </ul>
                    <!-- resume links -->
                     <ul class="navbar-nav d-flex flex-row">
                    <li>
                        <a href="{% static 'image/IsaiahOlaoye.pdf' %}" class="btn btn-info btn-sm m-1" role="button">Resume</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="smooth-scroll nav-link m-1" href="{% url 'projects:account' %}">Account</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="smooth-scroll nav-link m-1" href="{% url 'projects:account' %}">Dashboard</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li>
                      <a href="{% url 'projects:user_logout' %}" class="btn btn-red btn-sm m-1 font-larger" role="button">Logout</a>
                    </li>
                    {% else %}
                    <li>
                      <a href="{% url 'projects:user_login' %}" class="btn btn-green btn-sm m-1 font-larger" role="button">Login</a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
        <!-- background image -->
    </navbar>
    <header>
        <!-- Full Page Intro -->
        <div class="view grey lighten-3">
            <!-- Mask & flexbox options-->
            <div class="mask">
                <!-- Content -->
                <div class="container h-100">
                    <!--Grid row-->
                    <div class="row align-items-center h-100">
                        <!--Grid column-->
                        <div class="col-md-6">
                            <h1 class="mb-4">Welcome, <span class="text-warning">{{user.username }}.</span><br><span
                                    class="cyan-text">Hello!</span> I'm here to help.</h1>
                            <a href="{% url 'projects:upload' %}"><button type="button"
                                    class="btn btn-primary btn-rounded btn-md ml-md-0">Upload your Projects</button></a>
                            <a href="{% url 'projects:update' %}"><button type="button"
                                    class="btn btn-outline-grey btn-rounded btn-md">Update your info</button></a>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-md-6">
                            <img src="https://mdbootstrap.com/img/illustrations/hiker-man-colour.svg" alt=""
                                class="img-fluid">
                        </div>
                        <!--Grid column-->
                    </div>
                    <!--Grid row-->
                </div>
                <!-- Content -->
            </div>
            <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->

    </header>
</body>
<!-- Footer -->
<!-- End your project here-->

<!-- jQuery -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- MDB -->

<!-- Your custom scripts (optional) -->

</html>

projects/templates/project/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Login-page
{% endblock %}


{% block content %}

    <!--Section: Content-->
    <section class="my-5 p-5 text-center" style="background-color:#02121ff1;
        background-size: cover;">

        <form action="{% url 'projects:user_login' %}" method="POST" class="my-5 mx-md-5">
            {% csrf_token %}
            <div class="row d-flex justify-content-center">
                <h2 class="green-text text-center">Sign in to post your Project</h2>
                <div class="col-md-6">
                    <h5 class="red-text">{{error}}</h5>
                    <!-- Username -->
                    <div class="form-outline mb-4">
                        <input type="text" name="username" id="id_username" class="form-control" required
                            placeholder="Username" />
                        <label for="id_username">Username</label>
                    </div>
                    <br>
                    <!-- Password input -->
                    <div class="form-outline mb-4">
                        <input type="password" name="password" id="id_password" class="form-control" required />
                        <label for="id_password">Password</label>
                    </div>
                    <br>
                    <div class="text-center">
                        <!-- Simple link -->
                        <a class="text-info" href="#!">Forgot password?</a>
                    </div>
                    <hr>
                    <br>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-green btn-block mb-4">Sign in</button>
                </div>
            </div>
        </form>
    </section>
    <!-- section content -->

{% endblock %}

projects/templates/project/projectpage.html
{% extends 'base.html' %}
{% load static %}


{% block title %} projects {% endblock %}

{% block content %}


    <h1 class="text-center green-text wow lightSpeedIn my-4" data-wow-delay="0.5s" data-wow-duration='3s'>My projects
</h1>

<div class="row row-cols-1 row-cols-md-2 g-4">
    {% for pro in projects %}
    <div class="col">
        <div class="card view overlay zoom">
            <a href="{{ pro.url }}"><img src="{{ pro.ImageURL }}" class="card-img-top wow zoomInLeft"
                    data-wow-delay="0.4s" data-wow-duration='4s' alt="{{ pro.title }}" height="550"/></a>
            <div class="card-body">
                <br>
                <h3 class="card-title font-weight-bold cyan-text text-center">{{ pro.title }}</h3>
                <hr>
                <p class="card-text">
                <h5 class="indigo-text">{{ pro.description }}</h5>
                </p>
                <p class="amber-text"><i class="fas fa-code"></i> : <span class="text-primary">
                        {{ pro.software_used }}</span>
                </p>
                <div class="card-footer">
                    <small class="text-muted">Date created {{ pro.created|date:"D, j F Y" }}.</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
{% include '_paginator.html' with page=projects %}
</div>
{% endblock %}

projects/templates/project/updatepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}update-page{% endblock %}

{% block content %}
<div class="container my-5 py-5 z-depth-1">
    <h2 class="text-center text-primary">Welcome to your Dashboard, {{request.user.username|upper}}🤩😁</h2>
    <br>
    <hr>
    <h2 class="text-success text-center m-4">Update form</h2>
    <form method="POST" enctype="multipart/form-data" class="md-form">
        <div class="file-field">
            <div class="mb-4">
                <img src="{{ info.profileURL }}" class="rounded-circle z-depth-1-half avatar-pic"
                    alt="{{ info.username }}" style="width: 150px;">
            </div>
            <div class="d-flex">
                <div class="btn btn-mdb-color btn-rounded">
                    <span>Add photo</span>
                    <input type="file" name="profile_pic">
                </div>
            </div>
        </div>
        <div class="file-field medium">
            <div class="btn btn-rounded aqua-gradient">
                <span>Add background pic</span>
                <input type="file" name="background_pic">
            </div>
            <div class="file-path-wrapper">
                <input name="background_pic" class="file-path validate" type="text" placeholder="background pic">
            </div>
        </div>
        <!--Textarea with icon prefix-->
        <div class="md-form amber-textarea active-amber-textarea-2">
            <i class="fas fa-pencil-alt prefix"></i>
            <textarea id="form24" name="about_me" class="md-textarea form-control" rows="3"></textarea>
            <label for="form24">Who is Isaiah Olaoye?</label>
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <hr>
</div>
{% endblock %}

projects/templates/project/upload.html
{% extends 'base.html' %}
{% load static %}

{% block title %}upload-page{% endblock %}

{% block content %}
<div class="container my-5 py-5 z-depth-1">
    <p>
    <h2 class="text-center text-primary">Welcome to your Dashboard, {{user.username|upper}}🤩😁</h2>
    </p>
    <br>
    <hr>
    <h2 class="text-success text-center m-4">Fill in the right Info to upload form</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="md-form form-l">
            <input type="text" id="id_title" name='title' class="form-control form-control-lg">
            <label for="id_title">Title</label>
        </div>
        <div class="md-form amber-textarea active-amber-textarea-2">
            <i class="fas fa-pencil-alt prefix"></i>
            <textarea id="id_description" name="description" class="md-textarea form-control" rows="3"></textarea>
            <label for="id_description">Description</label>
        </div>
        <div class="input-group md-form form-sm form-1 pl-">
            <div class="input-group-prepend">
                <span class="input-group-text cyan lighten-2" id="basic-text1"><i class="fas fa-search text-white"
                        aria-hidden="true"></i></span>
            </div>
            <input class="form-control my-0 py-1" type="text" placeholder="URL" aria-label="URL" name="url">
        </div>
        <div class="file-field">
            <div class="btn btn-pink btn-rounded btn-sm">
                <span><i class="fas fa-upload mr-2" aria-hidden="true"></i>Upload picture</span>
                <input type="file" name="project_image">
            </div>
        </div>
        <div class="md-form form-l">
            <input type="text" id="id_software_used" name='software_used' class="form-control form-control-lg">
            <label for="id_software_used">Software Used</label>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <hr>
</div>
{% endblock %}

templates/_paginator.html
<nav aria-label="...">
    <ul class="pagination pagination-circle justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link m-2 text-white" href="?page={{ page.previous_page_number }}" tabindex="-1"
                aria-disabled="true">Previous</a>
        </li>
        {% endif %}
        <li class="page-item active" aria-current="page">
            <a class="page-link m-2 text-white" href="?page={{ page.number }}">{{ page.number }}<span
                    class="visually-hidden">(current)</span></a>
        </li>
        {% if page.has_next %}
        <li class="page-item" aria-current="page">
            <a class="page-link m-2 text-white" href="?page={{ page.next_page_number }}">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title> {% block title %}{% endblock %}</title>

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.css" rel="stylesheet" />
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.js"></script>
  <!-- online iinks -->

  <!-- manual links -->
  <!-- Font Awesome -->

  <!--logo link-->
  <link rel="icon" href="{% static 'image/kuhmasiilogo.png' %}" type="image/x-icon">

  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <!-- Custom styles -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
  <header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-scroll">
      <!-- Container wrapper -->
      <div class="container">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-togggler-icon d-flex justify-content
                -start align-items-center">
            <i class="fas fa-bars text-white"></i>
          </span>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="smooth-scroll nav-link" href="{% url 'projects:home_page' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="smooth-scroll nav-link" href="{% url 'projects:about_me' %}">About Me</a>
            </li>
            <li class="nav-item">
              <a class="smooth-scroll nav-link" href="{% url 'projects:home_page' %}">Features</a>
            </li>
            <li class="nav-item">
              <a class="smooth-scroll nav-link" href="{% url 'projects:project' %}">Latest Projects</a>
            </li>
          </ul>

          <!-- resume links -->
          <ul class="navbar-nav d-flex flex-row">
            <li>
                <a href="{% static 'image/IsaiahOlaoye.pdf' %}" class="btn btn-info btn-sm m-1" role="button">Resume</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="smooth-scroll nav-link m-1" href="{% url 'projects:account' %}">Account</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="smooth-scroll nav-link m-1" href="{% url 'projects:account' %}">Dashboard</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'projects:user_logout' %}" class="btn btn-red btn-sm m-1 font-larger"
                role="button">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'projects:user_login' %}" class="btn btn-green btn-sm m-1 font-larger"
                role="button">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <!-- Collapsible wrapper -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <!-- background image -->
  </header>
  <main>
    <div class="container py-5">
      {% block content %}
      {% endblock %}
    </div>
  </main>
  <!-- Footer -->
  <footer class="page-footer font-large special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1" href="https://www.facebook.com/isaiah.thunder.7/">
            <i class="fab fa-facebook-f blue-text"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1" href="https://www.twitter.com/kuhmasii/">
            <i class="fab fa-twitter cyan-text"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1" href="https://www.linkedin.com/in/isaiah-olaoye-2848551b2/">
            <i class="fab fa-linkedin-in light-blue-text"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->
    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2021 Copyright:
      <a href="{% url 'admin:index' %}">kuhmasii.pythonanywhere.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- MDB -->
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript">
    $(document).ready(function () {
      new WOW().init();
    });
  </script>

</body>

</html>